# This is a basic workflow to help you get started with Actions

name: Pull Requests

on:
  pull_request:
    branches: [ '**' ] # matches every branch
  workflow_dispatch:

jobs:
  jvm-build-job:
    runs-on: ubuntu-latest
    steps:
      # Clone git project
      - uses: actions/checkout@v2

      # Set up JDK 11
      - name: 'Set up JDK 11'
        uses: actions/setup-java@v1
        with:
          java-version: 11

      # Build and test the application
      - name: 'Build & Test'
        run: mvn clean package
